### ISSUE TITLE
Unsupported file type when adding shortcuts

### ISSUE THREAD

**Issue by LauraWebdev** [ryanrudolfoba/SteamOS-Waydroid-Installer#25]
Installation has been working wonderfully, however the final step (adding the shortcuts) seemingly failed. Adding them to Game Mode manually does seem to work, although I couldn't find steamos-nested-desktop.sh

OS Version: 3.5.7
OS Build: 20231122.1

```
INFO: widevine installation finished
Casualsnek script done.
Adding shortcuts to game mode. Please wait.
Unsupported file type
Android_Waydroid_Cage.sh shortcut has been added to game mode.
Unsupported file type
Android_Waydroid_Weston.sh shortcut has been added to game mode.
Unsupported file type
steamos-nested-desktop shortcut has been added to game mode.
Waydroid has been successfully installed!
```

**Comment by ryanrudolfoba** [comment]
Are you running the script on desktop mode? Not from an ssh or virtual tty session?

Usually that issue happens if Steam client cant be run because the script was called from an ssh or virtual tty session.

Other than that im not able to replicate the issue :(

Regarding steamos-nested-desktop, you can add it manually to Game Mode. This is built in to SteamOS, it is located in /usr/bin/steamos-nested-desktop

**Comment by LauraWebdev** [comment]
Ah, this might be it, I've ran the installer through SSH.
