### ISSUE TITLE
Kernel is not supported, exiting immediately 

### ISSUE THREAD

**Issue by sebap2004** [ryanrudolfoba/SteamOS-Waydroid-Installer#27]
I have kernel 6.1.52-valve10-1-neptune-61, and it says my kernel is not supported. Is that a problem with waydroid? How can I sort this out?

**Comment by ryanrudolfoba** [comment]
The script only works on SteamOS 3.5.7 , 3.5.13 and 3.5.14.

What SteamOS version are you on?

**Comment by sebap2004** [comment]
> The script only works on SteamOS 3.5.7 , 3.5.13 and 3.5.14.
> 
> What SteamOS version are you on?

I am on version 3.5.7

**Comment by ryanrudolfoba** [comment]
For some reason your SteamOS 3.5.7 kernel is different than mine. Mine shows 6.1.52-valve9-1-neptune-61, both on my LCD and OLED.

With that said I can't build for that kernel since my Steam Deck is not getting that version.

Please check this, another user has similar issue his 3.5.7 is on a different kernel too -

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/17

**Comment by ryanrudolfoba** [comment]
I use LCD and OLED and i dont have that kernel version.

**Comment by sebap2004** [comment]
> I use LCD and OLED and i dont have that kernel version.

Recently had some time to try this out and unfortunately trying the issue you gave me didn't fix the problem. I don't know why I have this kernel version 😅

**Comment by ryanrudolfoba** [comment]
Updated the script. This now support latest SteamOS Preview 3.5.15 - kernel 6.1.52-valve16-1-neptune-61

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/33
