### ISSUE TITLE
Wayland game mode shortcut should have Gamepad with Mouse trackpad controller scheme by default

### ISSUE THREAD

**Issue by The-MAZZTer** [ryanrudolfoba/SteamOS-Waydroid-Installer#31]
Not sure how doable this is but this is a better controller config default I think.

Currently it seems to default to Gamepad with Joystick trackpad. I didn't find that intuitive but maybe that's me.

**Comment by ryanrudolfoba** [comment]
This should be an easy fix. I:ll export as community profile the controller configuration. I'll update the README once completed most probably later today.

**Comment by ryanrudolfoba** [comment]
I tried to play a game using gamepad with mouse trackpad controller profile and it is un-intuitive for me. Since touchscreen works it is way better to use the touchscreen for mouse tasks.

This boils down to personal preference and not an issue with the script. I'll go ahead and close the issue. Please feel free to use preferred controller profile, customize if needed and export so the community can give it a go.

Please let me know and i will update the GitHub readme for an alternate community profile.
