### ISSUE TITLE
Brawl star not working 

### ISSUE THREAD

**Issue by Felzow47** [ryanrudolfoba/SteamOS-Waydroid-Installer#66]
Start on a black screen for 2-3 seconds and close itself

**Comment by ryanrudolfoba** [comment]
Some games do not work maybe because of anti cheat, or because of compatibility with the libndk arm translation layer.

Please check the spreadsheet here for apps / games tested by other members and please feel free to update it too with your games testing -

https://docs.google.com/spreadsheets/d/1pyqQw2XKJZBtGYBV0i7C510dyjVSU2YndhaTOEDavdU/edit?usp=sharing
