### ISSUE TITLE
install magisk and libs

### ISSUE THREAD

**Issue by Mstereme** [ryanrudolfoba/SteamOS-Waydroid-Installer#75]
Hello, could someone explain to me if it is possible and how to switch the lib (from libndk to libhoudini) and install magisk?

**Comment by ryanrudolfoba** [comment]
> switch the lib (from libndk to libhoudini)
you would need the casualsnek script to uninstall libndk translation layer and then install libhoudini translation layer. \
libndk is geared towards AMD, and libhoudini for Intel. so really you shouldnt use libhoudini on the Steam Deck. \
and libhoudini wont fit on the var partition so that wont work too.

> install magisk
same you will need the casualsnek script to install magisk. i tried several months ago magisk installs fine but still not able to root. afair you would also need a different kernel for magisk to work properly. let me know if you figure out magisk and i can update the script / process.
