### ISSUE TITLE
steamos 3.7 / widevine l3 > l1

### ISSUE THREAD

**Issue by slynobody** [ryanrudolfoba/SteamOS-Waydroid-Installer#82]
Thank you for your great effort.

three questions: 

1. would it be possible to also support steamos 3.7 (main-channel)? something like a dkms-solution would not work here?
2. would it be possible to have an option to remove google-playstore-support? (or even not install it in the first place)
3. is it possible to get widevine L1 somehow? currently it is L3. there are some dubious apks in the wild claiming to offer widevine L1-support. maybe you or someone else could explain what would be dependencies to get L1 or near it.
-  (side-question: could it be the video-solution has some sort of color-problem? videos seem to be in some sort of dithered mode?)

**Comment by ryanrudolfoba** [comment]
1 - SteamOS 3.7 I dont use that so I wont build the kernel modules for it. I'm on the initial testing for SteamOS 3.6 I've built the kernel module and it works. I want to incorporate the new features of SteamOS3.6 like /etc whitelist so that will take a while before I put out an updated script for 3.6 let alone 3.7

2. If you dont want gapps (google play) just edit the script on line 45 remove the GAPPS entry -
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/98122529/9c71ce22-e622-4408-b11d-bac8ac38f4c3)

3. afaik only widevine L3 is available which the script uses [here](https://github.com/casualsnek/waydroid_script)

**Comment by ryanrudolfoba** [comment]
1. SteamOS 3.7 I dont use that so I wont build the kernel modules for it. I'm on the initial testing for SteamOS 3.6 I've built the kernel module and it works. I want to incorporate the new features of SteamOS3.6 like /etc whitelist so that will take a while before I put out an updated script for 3.6 let alone 3.7

2. If you dont want gapps (google play) just edit the script on line 245 remove the GAPPS entry -\
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/98122529/9c71ce22-e622-4408-b11d-bac8ac38f4c3)

3. afaik only widevine L3 is available which the script uses [here](https://github.com/casualsnek/waydroid_script)

**Comment by slynobody** [comment]
thank you for your answers.

1. /etc-whitelist-stuff sounds great. dkms-support is not possible?
2. is it possible to remove GAPPS after former installation?
3. maybe someone else has insights how one possibly could get widevine L1? It could be the only working solution under linux so far to get hd at prime, disney etc.
4. magisk does not seem to work currently?

**Comment by ryanrudolfoba** [comment]
i dont use MAIN / SteamOS 3.7 so it will be difficult to provide support if something goes wrong on the script. Currently it only works on 3.5.19 stable and soon on 3.6

it might break if you remove gapps on a working install. i would suggest start fresh and edit the script so no gapps included.

widevine L1 no idea.

magisk doesnt work i got a headache figuring that one several months ago. :(
