### ISSUE TITLE
Steam Deck Storage Error [Error: Errno 28]

### ISSUE THREAD

**Issue by BeeperMiniSourceCode** [ryanrudolfoba/SteamOS-Waydroid-Installer#84]
I keep getting this error when I do ./steamos-waydroid-installer.sh
I tried switching it to the SD card and it didn't do anything

I'm using
Steam Deck LCD 64 GB Model
SteamOS V3.5.19

I am using Decky Loader Plugins:
ProtonDB Badges
Decky Recorder
Audio Loader
CSS Loader
SteamGridDB
![IMG_0005](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/154485916/c7c3cb9a-851c-4bf9-badc-f290b99e1622)

**Comment by ryanrudolfoba** [comment]
Based on the error it completed downloading the ~860MB image but have errors when extracting it due to insufficient disk space.

Please use this command to show free space -

df -h

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: BeeperMiniSourceCode ***@***.***>
Sent: Friday, May 17, 2024 12:38:19 AM
To: ryanrudolfoba/SteamOS-Waydroid-Installer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ryanrudolfoba/SteamOS-Waydroid-Installer] Steam Deck Storage Error [Error: Errno 28 (I think that's misspelled)] (Issue #84)


I keep getting this error when I do ./steamos-waydroid-installer.sh
I tried switching it to the SD card and it didn't do anything

I'm using
Steam Deck LCD 64 GB Model
SteamOS V3.5.19

I am using Decky Loader Plugins:
ProtonDB Badges
Decky Recorder
Audio Loader
CSS Loader
SteamGridDB
IMG_0005.JPEG (view on web)<https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/154485916/c7c3cb9a-851c-4bf9-badc-f290b99e1622>

**Comment by BeeperMiniSourceCode** [comment]
Ok I did that now what do I do?
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/154485916/287af7ae-7c93-457c-a3ec-e3e37e8f4d5d)
